# We use conda to install cromwell.

language: python

python:
  - 3.6

services:
  - docker

before_install:
  # Install conda
  - export MINICONDA=${HOME}/miniconda
  - export PATH=${MINICONDA}/bin:${PATH}
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p ${MINICONDA}
  - conda config --set always_yes yes
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge

stages:
  - test

stage: test

install:
  - conda install --file requirements-test.txt

script:
  - travis_wait 30 pytest --keep-workflow-wd-on-fail --tag $TEST tests/

after_failure:
  # Get the last 1000 lines of the cromwell log to catch the error.
  - bash -c 'tail -n 1000 /tmp/pytest_workflow_*/*/log.out'

matrix:
  include:
    - env: TEST="Womtool validate and submodule up to date."
      install:
        - conda install cromwell miniwdl wdl-aid
      script: bash scripts/biowdl_lint.sh
      after_failure:
        - echo "Linting failed"
    - env:
      - TEST="pacbio.integration.test"
    - env:
      - TEST="pacbio.no.transcriptclean"
    - env:
      - TEST="nanopore.integration.test"
    - env:
      - TEST="nanopore.no.transcriptclean"
